
# services:
#   metabase:
#     image: metabase/metabase:latest
#     container_name: metabase
#     ports:
#       - "3000:3000"
#     environment:
#       MB_DB_TYPE: postgres
#       MB_DB_DBNAME: ${METABASE_DB_NAME}
#       MB_DB_PORT: ${METABASE_DB_PORT}
#       MB_DB_USER: ${METABASE_DB_USER}
#       MB_DB_PASS: ${METABASE_DB_PASSWORD}
#       MB_DB_HOST: ${METABASE_DB_HOST}
#       MB_SITE_URL: ${MB_SITE_URL}
#       MB_SITE_NAME: ${MB_SITE_NAME}
#       MB_EMBEDDING_SECRET_KEY: ${METABASE_EMBEDDING_SECRET_KEY}
#       MB_ADMIN_EMAIL: ${MB_ADMIN_EMAIL}
#     depends_on:
#       - metabase-db
#     restart: always  # <- This ensures it starts on reboot
#     networks:
#       - metanet

#   metabase-db:
#     image: postgres:14
#     container_name: metabase-db
#     restart: always
#     environment:
#       POSTGRES_DB: ${METABASE_DB_NAME}
#       POSTGRES_USER: ${METABASE_DB_USER}
#       POSTGRES_PASSWORD: ${METABASE_DB_PASSWORD}
#     volumes:
#       - metabase_db_data:/var/lib/postgresql/data
#     networks:
#       - metanet

# volumes:
#   metabase_db_data:

# networks:
#   metanet:
#     driver: bridge
